In [15]:
# import necessary libraries
from pathlib import Path
import requests
import pandas as pd

def download_one_file(year: int, month: int, day: int) -> Path:
    """
    Downloads the yellow taxi trip data for a given year and month from Inside Airbnb and saves it as a csv file.

    Args:
    - year (int): The year of the data to download.
    - month (int): The month of the data to download.
    - day (int): The day of the data to download.

    Returns:
    - path (Path): The path to the downloaded csv file.
    """


    URL = f'http://data.insideairbnb.com/united-states/ny/new-york-city/{year}-{month:02d}-{day:02d}/visualisations/listings.csv'
    response = requests.get(URL)

    if response.status_code == 200:
        path = f'../data/raw/new-york-city/{year}-{month:02d}-{day:02d}.csv'
        open(path, 'wb').write(response.content)
        return path
    else:
        raise Exception(f'{URL} is not available.')

In [16]:
# explore and validate one single file
download_one_file(year=2023, month=10, day=1)

df = pd.read_csv('../data/raw/new-york-city/2023-10-01.csv')
df.head(20)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,2595,Rental unit in New York · ★4.68 · Studio · 1 b...,2845,Jennifer,Manhattan,Midtown,40.753560,-73.985590,Entire home/apt,240,30,49,2022-06-21,0.29,3,351,0,NaN
1,5121,Rental unit in Brooklyn · ★4.52 · 1 bedroom · ...,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.685350,-73.955120,Private room,66,30,50,2019-12-02,0.29,2,151,0,NaN
2,6848,Rental unit in Brooklyn · ★4.58 · 2 bedrooms ·...,15991,Allen & Irina,Brooklyn,Williamsburg,40.709350,-73.953420,Entire home/apt,81,30,191,2023-08-14,1.09,1,79,5,NaN
3,6872,Condo in New York · 1 bedroom · 1 bed · 1 shar...,16104,Kae,Manhattan,East Harlem,40.801070,-73.942550,Private room,65,30,1,2022-06-05,0.06,2,295,0,NaN
4,7064,Loft in Brooklyn · ★4.91 · 1 bedroom · 1 bed ·...,17297,Joelle,Brooklyn,Williamsburg,40.712480,-73.958810,Private room,95,30,13,2022-09-12,0.08,2,26,0,NaN
5,7097,Home in Brooklyn · ★4.88 · 1 bedroom · 2 beds ...,17571,Jane,Brooklyn,Fort Greene,40.691940,-73.973890,Private room,205,2,347,2023-09-24,2.08,2,280,38,OSE-STRREG-0000008
6,7801,Place to stay in Brooklyn · ★4.89 · 1 bed · 1 ...,21207,Chaya,Brooklyn,Williamsburg,40.718807,-73.956177,Entire home/apt,350,30,11,2023-09-16,0.06,1,245,2,NaN
7,8490,Loft in Brooklyn · ★4.77 · 1 bedroom · 4 beds ...,25183,Nathalie,Brooklyn,Bedford-Stuyvesant,40.684620,-73.938390,Entire home/apt,160,30,189,2023-08-21,1.10,2,343,32,NaN
8,9357,Rental unit in New York · ★4.52 · Studio · 1 b...,30193,Tommi,Manhattan,Hell's Kitchen,40.767240,-73.986640,Entire home/apt,175,45,58,2017-08-13,0.34,1,337,0,NaN
9,10452,Rental unit in Brooklyn · ★4.65 · 1 bedroom · ...,35935,Angela,Brooklyn,Bedford-Stuyvesant,40.682940,-73.956820,Private room,90,30,84,2023-09-16,0.51,4,122,2,NaN
10,11943,Home in Brooklyn · 1 bedroom · 2 beds · 1 bath,45445,Harriet,Brooklyn,Flatbush,40.637020,-73.963270,Private room,150,30,0,NaN,NaN,1,0,0,NaN
11,12192,Rental unit in New York · ★4.39 · 1 bedroom · ...,46978,Edward,Manhattan,East Village,40.722960,-73.983830,Private room,70,30,313,2023-09-16,1.85,1,154,29,NaN
12,12937,Townhouse in Queens · ★4.91 · 1 bedroom · 1 be...,50124,Orestes,Queens,Long Island City,40.747570,-73.945710,Private room,165,30,385,2023-09-20,2.38,1,217,46,NaN
13,12940,Rental unit in Brooklyn · ★4.52 · 1 bedroom · ...,50148,Adreinne,Brooklyn,Bedford-Stuyvesant,40.679460,-73.954170,Entire home/apt,125,30,76,2023-05-01,0.45,1,304,3,NaN
14,13808,Townhouse in Brooklyn · ★4.65 · 1 bedroom · 1 ...,54275,JT And Tiziana,Brooklyn,Bedford-Stuyvesant,40.680640,-73.940390,Private room,94,30,199,2023-09-20,1.23,2,0,25,NaN
15,14314,Rental unit in Brooklyn · ★4.82 · 1 bedroom · ...,56246,Jeanne,Brooklyn,Greenpoint,40.735350,-73.955840,Entire home/apt,129,30,180,2023-09-01,1.07,1,240,1,NaN
16,14434,Rental unit in Brooklyn · ★4.56 · 1 bedroom · ...,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.687770,-73.949760,Private room,70,30,60,2022-06-01,0.37,2,0,0,NaN
17,15341,Condo in New York · ★4.56 · 1 bedroom · 2 beds...,60049,Ted,Manhattan,Lower East Side,40.721359,-73.993668,Entire home/apt,173,30,37,2023-09-30,0.30,1,149,4,NaN
18,15385,Rental unit in Brooklyn · ★4.87 · 1 bedroom · ...,60252,Cristina,Brooklyn,Williamsburg,40.712110,-73.963970,Private room,92,30,55,2023-09-06,0.34,1,210,6,NaN
19,15396,Rental unit in New York · ★5.0 · 2 bedrooms · ...,60278,Petra,Manhattan,Chelsea,40.744930,-73.995210,Entire home/apt,400,90,5,2018-11-03,0.05,1,95,0,NaN